### ISSUE TITLE
Angular Component to Display Map

### ISSUE THREAD

**Issue by daebwae** [rfcx/web-components#5]
This is a description for an example feature.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296773/167313494639414)

**Comment by rassokhin-s** [comment]
At this task you need to create a component for displaying the map.

You should use [carto.js](https://carto.com/) service for map displaying.

In the code you'll see that there is a `Demo` page with `counter` component. You can take a look at them and create a separate page called `Map` with a link on the left nav and `rfcx-map` component inside it similarly to existing code. Please stick to this hierarchy and code style.

The html code of the component should look like:
`<rfcx-map center-lat="50.4032" center-lon="113.2612" zoom="1"></rfcx-map>`
This is a universal component's code, so I should be able to place it anywhere in the app and then see a map there.

Actually `center-lat`, `center-lon` and `zoom` attributes values could be defined via variables from the controller where this component is used.
Example: `<rfcx-map center-lat="map.lat" center-lon="map.lon" zoom="map.zoom"></rfcx-map>` where `map` is an object:
```
{
    lat: 50.4032,
    lon: 113.2612,
    zoom: 1
}
```
And the component should watch for changes in these attributes and drag/zoom the map according to these changes. For visual test purposes you can create simple form with text inputs for latitude, longitude and zoom with initial values from the task (50.4032, 113.2612 and 1) and Submit button. When I change some values to another and press Submit button, then the map moves to new position and changes zoom level.

**Notes**
1) There could be more than one map per page. They should not conflict between each other.
2) As it was mentioned in task #2, the map should be creating using [createLayer](https://carto.com/academy/courses/cartojs-ground-up/createvis-vs-createlayer/) approach.
3) At this task you don't need to create any child components. Only showing the map.
4) If there is a need to use a directive instead of component type, you can do it.

**Comment by pradyumnad** [comment]
Base maps information can be found here https://carto.com/location-data-services/basemaps/

**Comment by pradyumnad** [comment]
Basics of map creation using cartodb.js (https://carto.com/docs/tutorials/create_map_cartodbjs/)

**Comment by rassokhin-s** [comment]
Hey @pradyumnad! Nice work at this point!

I have some comments for you:

1) Is there any special purpose of using `self` variable in rfcxMapController? I think you can use `this` directly.
2) I guess the following stuff might be in development, but I asked to create a small form where we can change actual lat/lon and zoom and see that map refrects to these changes. Thanks.
3) Please do not use inline style tags or attributes if there is no need for that. You have .less file where you can write your styles.

And a small bug:

1) When I click on the Map link on sidebar, it opens a Map page, but Home icon stays active. Expectation: Map icon should become active.

**Comment by pradyumnad** [comment]
Hi @rassokhin-s,
Thanks for the detailed feedback.

1) When we use `this` in any anonymous function, it uses the function as the reference rather than the component. That is the reason I have put a reference as `self`.
2) I have not implemented that feature yet.
3) Sorry, totally forgot about that point, I will make changes to that.

There are more changes coming up and all of these will be addressed.

**Comment by pradyumnad** [comment]
Hey @rassokhin-s,
Is the "Submit" button for the form compulsory? I am thinking of directly binding the `map.lat`, `map.lon` and `map.zoom` to the component so that the map shows whenever the form input is changed.

Let me know your thoughts on this.

**Comment by rassokhin-s** [comment]
Hey @pradyumnad 
For the **(1)** point:
I know this "hack" - we can use `this` via `self` or `_this` or another variable in (for example) callbacks where `this` represents another context. But I guess in your code no need to use `self`, because `this` is properly defined in all parts of `rfcxMapController` code. I also tried to replace `self` with `this` and it worked well. Please let me know if I missed smth.
Also there is another more professional approach how to use `this` in such methods: [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind). So you can simply add `.bind(this)` after method and it will handle this context.

And now for your question about Submit button. Your approach of immediately reflection to inputs change is great, but I'd prefer not to move/zoom map until user finally change input to his value. I describe what I mean: 
e.g. User has `zoom == 5`, he wants to change it to `12`. He starts to type number `1` and map zooms to `1`, then he types second symbol `3` and map zooms to `13`. 
another example: user has lat/lon == 50.4032/113.2612. He wants to change them to 34.123/100.22. Then he starts from lat: by typing 34.123 his map will jump to 34.123/113.2512 (which is totally different place from the first point and result point)...
I prefer not to `jump` map such way. You can tell that we can create a timeout, but I'd prefer to let user decide when he ready to move his map :)

Anyway - thank you for asking this! The form with lat/lon and zoom is only for our internal testing purpose, so there is no need to spend a lot time on it.

**Comment by pradyumnad** [comment]
Hey @rassokhin-s,

Thanks for the detailed explanation, I appreciate your patience in giving such details.
I convinced myself with the same explanation you gave me but I asked you for confirmation :)

I made one more commit, addressing the issues and the test form to play with map. Let me know if I need to do any changes.

**Comment by rassokhin-s** [comment]
Hi @pradyumnad!

That's what I talked about, great! Thank you!

Few notes:
- Sorry for mentioning this only now, but I've got an idea few days ago: as long as we have a separate component for map layers (rfcxBasemap) I think it's better to keep `BaseMapType` (src/app/components/rfcx-map/rfcx-map.component.js:17) in `rfcxBasemap` controller's file (not in `rfcxMap` controller), because they are directly connected with layer's component. Then you can simplify your `this.addBaseLayer` method of `rfcxMap` component with only one line:
```
this.addBaseLayer = function(layer) {
  this.rfcxMap.addLayer(layer);
};
```
and move all logic of creating a layer to component which should create a layer :) Does that make sense?

- Also you have layer's attribute named `from="carto"`, but you don't use this value. I guess it could be used in your `BaseMapType` variable as an attribute containing layer data.
- Please append another one or two <rfcx-basemap> components to the map, so we can be sure that several layers are correctly appended to the map and we can switch them.
- Also your components require some unit-tests ;)

And once again: nice job! Keep up the good work! :)
